CREATE DATABASE PLANTAS;
GO

USE PLANTAS;
GO

CREATE TABLE CATEGORIA (
    ID INT IDENTITY,
    CATEGORIA VARCHAR(50) NOT NULL,
    CONSTRAINT PK_IDCATEGORIA PRIMARY KEY (ID)
);

CREATE TABLE PLANTA (
    ID INT IDENTITY,
    NOMBRE VARCHAR(50) NOT NULL,
    CATEGORIAID INT NOT NULL,
    CONSTRAINT PK_IDPLANTA PRIMARY KEY (ID),
    CONSTRAINT FK_PLANTA_CATEGORIA FOREIGN KEY (CATEGORIAID) REFERENCES CATEGORIA(ID)
);
